# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true

# Setup
title:               "Ithaca Nei Gong"
email:               "mark@ithacaneigong.com"
tagline:             "Lotus Nei Gong certified training"
description:         "Qi Gong training in Ithaca, NY"
url:                 "http://ithacaneigong.com"
baseurl:             ''
#paginate:            5
#paginate_path:       "page:num"

include: ['_pages', '_assets', '_posts', '_images']

google_analytics:    G-HT1MFFCZP5

# About/contact
author:
  name:              "Mark Reichert"
  url:               "http://ithacaneigong.com"
  email:             "mark@ithacaneigong.com"

# Custom vars
version:             1.0.0

# Fix build error
github: [metadata]

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
exclude:
  - Gemfile
  - Gemfile.lock
