# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true

# Setup
title:               QuietSlow
email:               mark@quietslow.com
tagline:             Lotus Nei Gong certified training in upstate NY
description:         Qi Gong training in Ithaca, NY
url:                 http://quietslow.com
baseurl:             ''
#paginate:            5
#paginate_path:       "page:num"

include: ['_pages', '_assets', '_posts']

# About/contact
author:
  name:              Mark Reichert
  url:               http://quietslow.com
  email:             mark@quietslow.com

# Custom vars
version:             1.0.0

# Fix build error
github: [metadata]

plugins:
  - jekyll-feed
#  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
